### PR TITLE
add rest reporter

### PR DESCRIPTION
**Pull request by bryanstern**

### CODE REVIEW

**Comment by jonschmidt** [comment]
@bryanstern this seems pretty useful. Can I ask why this was closed?

**Comment by bryanstern** [comment]
The project appeared unmaintained at the time and I ended up going in another direction for my project.

**Comment by passy** [comment]
Well, I'm still here. :)

**Comment by jonschmidt** [comment]
hah. fair enough. Were you happy with your implementation for the most part @bryanstern ? I need something similar.

**Comment by passy** [comment]
Yeah, that looked good to me. :)

**Comment by jonschmidt** [comment]
I checked this out and tested it and it seems to work fine for what I am trying to do. My guess is @bryanstern did not want to go through the trouble of getting it into master, but as far as I am concerned, it works. I am going to use my fork for now, but would love to see this or something comparable revived!

**Pull request closed without merging**
